grep: sgrep.c                                                                                                                                                                                                                              
        gcc -Wall -Werror -std=c11 -o sgrep sgrep.c
clean:
        rm sgrep
